[tool.poetry]
name = "circuitron"
version = "0.1.0"
description = "Agentic PCB design accelerator"
authors = ["Shaurya Sethi"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.110"
uvicorn = {extras = ["standard"], version = "^0.29"}
pydantic = "^2.7"
langchain = "^0.1"
skidl = "^2.0.1"
structlog = "^24.1"
streamlit = "^1.35"

[tool.poetry.group.dev.dependencies]
black = "^24.3"
ruff = "^0.3"
isort = "^5.13"
pre-commit = "^3.7"
pytest = "^8.2"
pytest-asyncio = "^0.23"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 88

[tool.isort]
profile = "black"

[tool.ruff]
line-length = 88
